[52948 | 47792 | ERROR | main.py:164] 2022-04-11 22:57:28,118: ERR : Traceback (most recent call last):
  File "K:/DEVELOPMENT/PYTHON_SAMPLE/DEV_PYTHON_BOT/main.py", line 155, in <module>
    mysql.SelMysq(opt='START')
AttributeError: module 'mysql' has no attribute 'SelMysq'

[52544 | 50340 | ERROR | Errlog.py:32] 2022-04-11 23:14:16,267: ERR : ERR : Traceback (most recent call last):
  File "K:/DEVELOPMENT/PYTHON_SAMPLE/DEV_PYTHON_BOT/main.py", line 129, in <module>
    mysql.SelMysq(opt='START')
AttributeError: module 'mysql' has no attribute 'SelMysq'

[55704 | 47480 | ERROR | Errlog.py:37] 2022-04-12 21:29:36,150: ERR : ERR : NoneType: None

[48172 | 39852 | ERROR | Errlog.py:37] 2022-04-12 21:49:01,769: ERR : ERR : NoneType: None

[16856 | 53216 | ERROR | Errlog.py:37] 2022-04-12 21:49:57,890: ERR : ERR : NoneType: None

[47384 | 56528 | ERROR | Errlog.py:37] 2022-04-12 21:51:01,531: ERR : ERR : NoneType: None

[52500 | 57320 | ERROR | Errlog.py:37] 2022-04-13 22:00:18,923: ERR : ERR : NoneType: None

[61416 | 11436 | ERROR | Errlog.py:37] 2022-04-14 11:16:25,508: ERR : ERR : NoneType: None

[19780 | 15348 | ERROR | Errlog.py:37] 2022-04-16 01:49:11,074: ERR : NoneType: None

[17592 | 8200 | ERROR | Errlog.py:37] 2022-04-16 01:50:13,866: ERR : NoneType: None

[16524 | 10332 | ERROR | Errlog.py:37] 2022-04-16 01:51:36,136: ERR : NoneType: None

[16348 | 15868 | ERROR | Errlog.py:37] 2022-04-16 03:18:14,822: ERR : NoneType: None

[26024 | 9988 | ERROR | Errlog.py:37] 2022-04-16 15:29:24,553: ERR : NoneType: None

[1816 | 21460 | ERROR | Errlog.py:37] 2022-04-16 15:42:20,074: ERR : Traceback (most recent call last):
  File "K:\DEVELOPMENT\PYTHON_SAMPLE\DEV_PYTHON_BOT\Practics\Package\mysql.py", line 78, in SelMysql
    MariaDB.StartMysql(self=MariaDB)
  File "K:\DEVELOPMENT\PYTHON_SAMPLE\DEV_PYTHON_BOT\Practics\Package\mysql.py", line 60, in StartMysql
    self.SetMysql()
TypeError: SetMysql() missing 1 required positional argument: 'self'

[1816 | 21460 | ERROR | Errlog.py:37] 2022-04-16 15:42:20,074: ERR : Traceback (most recent call last):
  File "K:\DEVELOPMENT\PYTHON_SAMPLE\DEV_PYTHON_BOT\Practics\Package\mysql.py", line 80, in SelMysql
    MariaDB.EndMysql(self=MariaDB)
  File "K:\DEVELOPMENT\PYTHON_SAMPLE\DEV_PYTHON_BOT\Practics\Package\mysql.py", line 66, in EndMysql
    self.SetMysql()
TypeError: SetMysql() missing 1 required positional argument: 'self'

[1816 | 21460 | ERROR | Errlog.py:37] 2022-04-16 15:42:20,074: ERR : NoneType: None

[23792 | 22664 | ERROR | Errlog.py:37] 2022-04-16 15:45:57,702: ERR : NoneType: None

[12440 | 9740 | Errlog.py:38] 2022-04-16 15:54:09,807: MESSAGE : NoneType: None

[26548 | 26080 | Errlog.py:38] 2022-04-16 15:54:22,423: MESSAGE : NoneType: None

